These Terms and Conditions (the “Terms”) are a legal contract between you and CollegeDays. These Terms explain how you are permitted to use the CollegeDays web application and services, as well as the CollegeDays website located www.gocollegedays.com and any content therein (collectively, the “Services). Unless otherwise specified, all references to the “Services” include the services available through the CollegeDays web application and the CollegeDays website, as well as any software that CollegeDays provides to you that allows you to access the Services from a Web device. By using the Services, you are agreeing to all of the Terms; if you do not agree with any of these Terms, do not access or otherwise use the Services. 
Changes to our Terms.
CollegeDays may make changes to the content and Services at any time. CollegeDays can change, update, or add or remove provisions of these Terms, at any time by posting the updated Terms on the Services or by notifying you via the App. By using the Services after CollegeDays has updated the Terms, you are agreeing to all the updated Terms; if you do not agree with any of the updated Terms, you must stop using Services.
General Use.
By using, you represent, acknowledge and agree that you are at least 18 years of age, or if you are under 18 years of age, but are at least 17 years old (a “Minor”), that that you have received your parent’s or legal guardian’s permission to use the Services and agree to these Terms. If you are a parent or legal guardian of a Minor, you hereby agree to bind the Minor to these Terms and to fully indemnify and hold harmless CollegeDays if the Minor breaches any of these Terms. If you are not at least 17 years old, you may not use the Services at any time or in any manner or submit any information to the CollegeDays or the Services.
CollegeDays provides content through the Services that is copyrighted and/or trademarked work of CollegeDays or CollegeDays’s third-party licensors and suppliers or other users of the Services (collectively, the “Materials”). Materials may include logos, graphics, video, images, software and other content.
Subject to the terms and conditions of these Terms, and your compliance with these Terms, CollegeDays hereby grants you a limited, personal, non-exclusive and non-transferable license to use and to display the Materials and to use the Services solely for your personal use. Except for the foregoing license, you have no other rights in the Services or any Materials and you may not modify, edit, copy, reproduce, create derivative works of, reverse engineer, alter, enhance or in any way exploit any of the Services or Materials in any manner.
If you breach any of these Terms, the above license will terminate automatically and you must immediately destroy any downloaded or printed Materials.
Web Applications.
The Services are made available via Web Applications. To use the Web Application you must have a Web device that is compatible with the Web service. CollegeDays does not warrant that the Web Application will be compatible with your Web device. CollegeDays hereby grants to you a non-exclusive, non-transferable, revocable license to use an object code copy of the Web Application for one registered account on one Web device owned or leased solely by you, for your personal use. You may not: (i) modify, disassemble, decompile or reverse engineer the Web Application, except to the extent that such restriction is expressly prohibited by law; (ii) rent, lease, loan, resell, sublicense, distribute or otherwise transfer the Web Application to any third-party or use the Web Application to provide time sharing or similar services for any third-party; (iii) make any copies of the Web Application; (iv) remove, circumvent, disable, damage or otherwise interfere with security-related features of the Web Application, features that prevent or restrict use or copying of any content accessible through the Web Application, or features that enforce limitations on use of the Web Application; or (v) delete the copyright and other proprietary rights notices on the Web Application. You acknowledge that CollegeDays may from time to time issue upgraded versions of the Web Application, and may automatically electronically upgrade the version of the Web Application that you are using on your Web device. You consent to such automatic upgrading on your Web device, and agree that these Terms will apply to all such upgrades. The foregoing license grant is not a sale of the Web Application or any copy thereof, and CollegeDays and its third-party licensors or suppliers retain all right, title, and interest in and to the Web Application (and any copy of the Web Application). Standard carrier data charges may apply to your use of the Web Application.
The following additional terms and conditions apply with respect to any Web Application that CollegeDays provides to you designed for use on an Apple iOS-powered Web device (an “iOS App”):
•	You acknowledge that these Terms are between you and CollegeDays only.
•	You represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (ii) You are not listed on any U.S. Government list of prohibited or restricted parties.
•	You agree to comply with all applicable third-party terms of agreement when using our web client (e.g., you must not be in violation of your wireless data service terms of agreement when using the Services).

Electronic Communications.
By using the Services, you consent to receiving electronic communications from CollegeDays. These electronic communications may include notices about applicable matches and account alerts, transactional information and other information concerning or related to the Services. These electronic communications are part of your relationship with CollegeDays. You agree that any notices, agreements, disclosures or other communications that we send you electronically will satisfy any legal communication requirements, including that such communications be in writing.
Privacy Policy.
Please review CollegeDays Privacy Policy (the “Privacy Policy”), available at [http://www.gocollegedays.com/privacy] which explains how we use information that we collect about you. By using our Services, you agree that we may use and disclose the information we collect about you as stated in the Privacy Policy. Without limiting the foregoing, you expressly acknowledge that any Submissions (defined below) or other information you submit to the Services may be viewable by all other users of the Services and any third party.
Submissions.
You are responsible for any information, opinions, messages, comments, photos, videos, graphics, sounds and other content or material that you submit, upload, post or otherwise make available on or through the Services (each a “Submission”) and through the Services available in connection with the Services. We reserve the right to retain your Submissions, even after they have expired from view within the App or even after you have deleted them. However, you agree that we have no obligation to retain any Submission for any period of time, nor shall we be responsible or liable to you or any third party for any lost content or losses related to the expiration or deletion of a Submission.
You may not upload, post or otherwise make available on the Services any material protected by copyright, trademark, or any other proprietary right without the express permission of the owner of such copyright, trademark or other proprietary right owned by a third-party, and the burden of determining whether any material is protected by any such right is on you. You shall be solely liable for any damage resulting from any infringement of copyrights, trademarks, proprietary rights, violation of contract, privacy or publicity rights or any other harm resulting from any Submission that you make. You have full responsibility for each Submission you make, including its legality, reliability and appropriateness.
Unless otherwise explicitly stated herein or in CollegeDays Privacy Policy, you agree that any Submission provided by you in connection with the Services is provided on a non-proprietary and non-confidential basis. You hereby grant to CollegeDays a non-exclusive, perpetual, irrevocable, royalty-free, fully paid-up, worldwide license (including the right to sublicense through multiple tiers) to use, reproduce, process, adapt, publicly perform, publicly display, modify, prepare derivative works, publish, transmit and distribute each of your Submissions, or any portion thereof, in any form, medium or distribution method now known or hereafter existing, known or developed, and authorize others to use the Submissions. We may modify or adapt your Submissions in order to transmit, display or distribute them over computer networks and in various media and/or make changes to the Submissions as necessary to conform and adapt them to any requirements or limitations of any networks, devices, services or media.
You agree to pay for all royalties, fees, damages and any other monies owing any person by reason of any Submissions posted by you to or through the Services. When you provide Submissions you agree that those Submissions shall not be in violation of the “Unauthorized Activities” paragraph below. Those prohibitions do not require CollegeDays to monitor, police or remove any Submissions or other information submitted by you or any other user.
Unauthorized Activities.
When using the Services and/or the services, you agree not to:
•	Defame, abuse, harass, stalk, threaten, or otherwise violate the legal rights (such as rights of privacy and publicity) of others.
•	Use racially or ethnically offensive language.
•	Discuss or incite illegal activity.
•	Post anything that exploits children or minors (including pornography that depicts minors) or that depicts cruelty to animals.
•	Post any copyrighted or trademarked materials without the express permission from the owner.
•	Disseminate any unsolicited or unauthorized advertising, promotional materials, ‘junk mail’, ‘spam’, ‘chain letters’, ‘pyramid schemes’, or any other form of such solicitation.
•	Use any robot, spider, scraper or other automated means to access the Services.
•	Take any action that imposes an unreasonable or disproportionately large load on our infrastructure.
•	Alter the opinions or comments posted by others on the Services.
•	Post anything contrary to our public image, goodwill or reputation.
This list of prohibitions provides examples and is not complete or exclusive. CollegeDays reserves the right to (a) terminate access to your account, your ability to post to the Services (or use the Services) and (b) refuse, delete or remove any Submissions; with or without cause and with or without notice, for any reason or no reason, or for any action that CollegeDays determines is inappropriate or disruptive to the Services or to any other user of the Services. CollegeDays may report to law enforcement authorities any actions that may be illegal, and any reports it receives of such conduct. When legally required or at CollegeDays’s discretion, CollegeDays will cooperate with law enforcement agencies in any investigation of alleged illegal activity on the Services or on the Internet.
Unauthorized use of any Materials or Third-Party Content contained in the Services may violate certain laws and regulations. You agree to indemnify and hold CollegeDays and its officers, directors, employees, affiliates, agents, licensors, and business partners harmless from and against any and all costs, damages, liabilities, and expenses (including attorneys’ fees and costs of defense) CollegeDays or any other indemnified party suffers in relation to, arising from, or for the purpose of avoiding, any claim or demand from a third-party that your use of the Services or the use of the Services by any person using your user name and/or password (including without limitation, your participation in the posting areas or, your Submissions) violates any applicable law or regulation, or the copyrights, trademark rights or other rights of any third-party.


Intellectual Property Infringement.
CollegeDays respects the intellectual property rights of others, and we ask you to do the same. CollegeDays may, in appropriate circumstances and at our discretion, terminate service and/or access to the Services for users who infringe the intellectual property rights of others. If you believe that your work is the subject of copyright infringement and/or trademark infringement and appears on our Site, please provide CollegeDays’s designated agent the following information:
•	A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
•	Identification of the copyrighted and/or trademarked work claimed to have been infringed, or, if multiple works at a single online site are covered by a single notification, a representative list of such works at that site.
•	Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled at the Services, and information reasonably sufficient to permit CollegeDays to locate the material.
•	Information reasonably sufficient to permit CollegeDays to contact you as the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which you may be contacted.
•	A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright and/or trademark owner, its agent, or the law.
•	A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
Submitting a DMCA Counter-Notification
We will notify you that we have removed or disabled access to copyright-protected material that you provided, if such removal is pursuant to a valid DMCA take-down notice that we have received. If you receive such notice from us, you may provide us with a counter-notification in writing to CollegeDays designated agent that includes all of the following information:
•	Your physical or electronic signature;
•	Identification of the material that has been removed or to which access has been disabled, and the location at which the material appeared before it was removed or access to it was disabled;
•	A statement from you under the penalty of perjury, that you have a good faith belief that the material was removed or disabled as a result of a mistake or misidentification; and
•	Your name, physical address and telephone number, and a statement that you consent to the jurisdiction of a court for the judicial district in which your physical address is located, or if your physical address is outside of the United States, for any judicial district in which CollegeDays may be located, and that you will accept service of process from the person who provided notification of allegedly infringing material or an agent of such person.
Termination of Repeat Infringers
CollegeDays reserves the right, in its sole discretion, to terminate the account or access of any user of our web site and/or service who is the subject or repeated DMCA or other infringement notifications.
Disclaimer of Warranties.
Your use of the Services and/or the Services is at your own risk. The Materials have not been verified or authenticated in whole or in part by CollegeDays, and they may include inaccuracies or typographical or other errors. CollegeDays does not warrant the accuracy of timeliness of the Materials contained on the Services. CollegeDays has no liability for any loss of, or errors or omissions in Submissions, or for any errors or omissions in the Materials, whether provided by CollegeDays, our licensors or suppliers or other users.
COLLEGEDAYS, FOR ITSELF AND ITS LICENSORS, MAKES NO EXPRESS, IMPLIED OR STATUTORY REPRESENTATIONS, WARRANTIES, OR GUARANTEES IN CONNECTION WITH THE SERVICES, THE SERVICES, OR ANY MATERIALS RELATING TO THE QUALITY, SUITABILITY, TRUTH, ACCURACY OR COMPLETENESS OF ANY INFORMATION OR MATERIAL CONTAINED OR PRESENTED ON THE SERVICES, INCLUDING WITHOUT LIMITATION THE MATERIALS. UNLESS OTHERWISE EXPLICITLY STATED, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES, THE SERVICES, AND MATERIALS AND ANY INFORMATION OR MATERIAL CONTAINED OR PRESENTED ON THE SERVICES IS PROVIDED TO YOU ON AN “AS IS,” “AS AVAILABLE” AND “WHERE-IS” BASIS WITH NO WARRANTY OF IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF THIRD-PARTY RIGHTS. COLLEGEDAYS DOES NOT PROVIDE ANY WARRANTIES AGAINST VIRUSES, SPYWARE OR MALWARE THAT MAY BE INSTALLED ON YOUR COMPUTER.
Limitation of Liability.
COLLEGEDAYS SHALL NOT BE LIABLE TO YOU FOR ANY DAMAGES RESULTING FROM YOUR DISPLAYING, COPYING, OR DOWNLOADING ANY MATERIALS TO OR FROM THE SERVICES. IN NO EVENT SHALL COLLEGEDAYS BE LIABLE TO YOU FOR ANY INDIRECT, EXTRAORDINARY, EXEMPLARY, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES (INCLUDING LOSS OF DATA, REVENUE, PROFITS, USE OR OTHER ECONOMIC ADVANTAGE) HOWEVER ARISING, EVEN IF COLLEGEDAYS KNOWS THERE IS A POSSIBILITY OF SUCH DAMAGE.
Local Laws; Export Control.
CollegeDays controls and operates the Services from its headquarters in the United States of America and the Materials may not be appropriate or available for use in other locations. If you use the Services outside the United States of America, you are responsible for following applicable local laws.
Feedback.
If you send or transmit any communications, comments, questions, suggestions, or related materials to CollegeDays, whether by letter, email, telephone, or otherwise (collectively, “Feedback”), suggesting or recommending changes to the Services, any Services offered through the Services or Materials, including, without limitation, new features or functionality relating thereto, all such Feedback is, and will be treated as, non-confidential and non-proprietary. You hereby assign all right, title, and interest in, and CollegeDays is free to use, without any attribution or compensation to you, any ideas, know-how, concepts, techniques, or other intellectual property and proprietary rights contained in the Feedback, whether or not patentable, for any purpose whatsoever, including but not limited to, developing, manufacturing, having manufactured, licensing, marketing, and selling, directly or indirectly, products and services using such Feedback. You understand and agree that CollegeDays is not obligated to use, display, reproduce, or distribute any such ideas, know-how, concepts, or techniques contained in the Feedback, and you have no right to compel such use, display, reproduction, or distribution.
General.
CollegeDays prefers to advise you if we feel you are not complying with these Terms and to recommend any necessary corrective action. However, certain violations of these Terms, as determined by CollegeDays, may result in immediate termination of your access to the Services without prior notice to you. The Federal Arbitration Act, Washington state law and applicable U.S. federal law, without regard to the choice or conflicts of law provisions, will govern these Terms. Foreign laws do not apply. The United Nations on Contracts for the International Sale of Goods and any laws based on the Uniform Computer Information Transactions Act (UCITA) shall not apply to this Agreement. Except for Disputes subject to arbitration as described above, any disputes relating to these Terms or the Services will be heard in the courts located in King County in the State of Washington. If any of these Terms is found to be inconsistent with applicable law, then such term shall be interpreted to reflect the intentions of the parties, and no other terms will be modified. CollegeDays’s failure to enforce any of these Terms is not a waiver of such term. These Terms are the entire agreement between you and CollegeDays and supersede all prior or contemporaneous negotiations, discussions or agreements between you and CollegeDays about the Services. The proprietary rights, disclaimer of warranties, representations made by you, indemnities, limitations of liability and general provisions shall survive any termination of these Terms.
Contact Us.
If you have any questions about these Terms or otherwise need to contact CollegeDays for any reason, you can reach us at [http://www.yikyakapp.com/support].

